_target_: src.models.narrative_model.NarrativeModel

len_ques: 42
len_para: 170
len_ans: 15
n_layers_trans: 3
n_heads_trans: 4
d_hid: 64
d_bert: 768
d_vocab: 30522
lr: 1e-5
w_decay: 1e-2
switch_frequency: 4
beam_size: 20
n_gram_beam: 8

path_pred: ${PATH.pred}
path_train_pred: ${PATH.train_pred}
